services:
  - type: web
    name: smart-fleet-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. gunicorn Backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Backend.settings
      - key: PYTHON_VERSION
        value: 3.11
