# Generated by Django 5.2.3 on 2025-06-29 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_expiry_date", models.DateField(blank=True, null=True)),
                ("availability", models.BooleanField(default=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("joining_date", models.DateField(auto_now_add=True)),
                ("experience_years", models.PositiveIntegerField()),
                ("emergency_contact", models.CharField(max_length=15)),
                (
                    "assigned_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drivers",
                        to="vehicles.vehicle",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
