# Generated by Django 5.2.3 on 2025-06-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("oil_change", "Oil Change"),
                            ("engine_check", "Engine Check"),
                            ("brake_service", "Brake Service"),
                            ("tire_rotation", "Tire Rotation"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("cost", models.FloatField()),
                ("km_at_service", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
